# This is free and unencumbered software released into the public domain.

name: build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Based on https://github.com/orgs/community/discussions/25678
      - name: Delete tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Login to registry
        if: github.ref == 'refs/heads/master'
        run: >-
          podman login ghcr.io
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}

      # Run before build as the images are big enough that GitHub will
      # only host one per repository before hitting the size limits
      - name: Purge old versions
        if: github.ref == 'refs/heads/master'
        run >-
          gh api \
          --method delete \
          --header 'accept: application/vnd.github+json' \
          --header 'x-github-api-version: 2022-11-28' \
          /users/ngarside/packages/container/${{ inputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_PURGE }}

      - name: Build image
        run: >-
          podman build
          --file ${{ inputs.name }}/${{ inputs.name }}.containerfile
          --format docker
          --progress plain
          --security-opt label=disable
          --tag ghcr.io/ngarside/${{ inputs.name }}:latest
          .

      - name: Push image to registry
        if: github.ref == 'refs/heads/master'
        run: podman push ghcr.io/ngarside/${{ inputs.name }}:latest
