# This is free and unencumbered software released into the public domain.

name: zen

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: 0 3 * * 1
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      name: zen
